REM as test.S –o test.o: 
REM this command converts the given assembly code into respective object code 
rem which is an intermediate code generated by the assembler before converting into machine code.

objcopy -O binary -j .text test.out test.binary
